INFO:werkzeug: * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.18.160:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:15:22] "GET /api/v1/status HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:15:28] "[31m[1mGET /api/v1/users HTTP/1.1[0m" 401 -
CRITICAL:root:None
CRITICAL:root:None
CRITICAL:root:(None, None)
ERROR:app:Exception on /api/v1/users [GET]
Traceback (most recent call last):
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/app.py", line 42, in before_request_handler
    if auth.current_user(request) is None:
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/auth/basic_auth.py", line 88, in current_user
    user_object = self.user_object_from_credentials(
TypeError: BasicAuth.user_object_from_credentials() missing 1 required positional argument: 'user_pwd'
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:15:34] "[35m[1mGET /api/v1/users HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:15:46] "[31m[1mGET / HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:15:46] "[31m[1mGET /favicon.ico HTTP/1.1[0m" 401 -
CRITICAL:root:test
CRITICAL:root:None
CRITICAL:root:(None, None)
ERROR:app:Exception on /api/v1/users [GET]
Traceback (most recent call last):
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/app.py", line 42, in before_request_handler
    if auth.current_user(request) is None:
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/auth/basic_auth.py", line 88, in current_user
    user_object = self.user_object_from_credentials(
TypeError: BasicAuth.user_object_from_credentials() missing 1 required positional argument: 'user_pwd'
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:16:28] "[35m[1mGET /api/v1/users HTTP/1.1[0m" 500 -
CRITICAL:root:Ym9iQGhidG4uaW86SDBsYmVydG9uU2Nob29sOTgh
CRITICAL:root:bob@hbtn.io:H0lbertonSchool98!
CRITICAL:root:('bob@hbtn.io', 'H0lbertonSchool98!')
ERROR:app:Exception on /api/v1/users [GET]
Traceback (most recent call last):
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/env/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/app.py", line 42, in before_request_handler
    if auth.current_user(request) is None:
  File "/home/ameralnas/alx-backend-user-data/0x01-Basic_authentication/api/v1/auth/basic_auth.py", line 88, in current_user
    user_object = self.user_object_from_credentials(
TypeError: BasicAuth.user_object_from_credentials() missing 1 required positional argument: 'user_pwd'
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:16:43] "[35m[1mGET /api/v1/users HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.18.160:5000 (Press CTRL+C to quit)
CRITICAL:root:None
CRITICAL:root:None
CRITICAL:root:(None, None)
CRITICAL:root:None
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:18:05] "[31m[1mGET /api/v1/users HTTP/1.1[0m" 403 -
CRITICAL:root:test
CRITICAL:root:None
CRITICAL:root:(None, None)
CRITICAL:root:None
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:18:24] "[31m[1mGET /api/v1/users HTTP/1.1[0m" 403 -
CRITICAL:root:Ym9iQGhidG4uaW86SDBsYmVydG9uU2Nob29sOTgh
CRITICAL:root:bob@hbtn.io:H0lbertonSchool98!
CRITICAL:root:('bob@hbtn.io', 'H0lbertonSchool98!')
CRITICAL:root:<models.user.User object at 0x7f604a052590>
INFO:werkzeug:127.0.0.1 - - [23/Jun/2024 18:18:31] "GET /api/v1/users HTTP/1.1" 200 -
